django/core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    # Custom apps
    path('', include('general.urls')),
    path('', include('researchdata.urls')),
    # Django admin
    path('dashboard/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/researchdata/urls.py
from django.urls import path
from . import views, apps

app_name = apps.app_name

urlpatterns = [
    path('sounds/exhibition/',
         views.SoundWelcomeTemplateView.as_view(),
         name='sound-welcome'),

    path('sounds/exhibition/sounds/',
         views.SoundListView.as_view(),
         name='sound-list'),

    path('sounds/exhibition/sounds/<pk>/',
         views.SoundDetailView.as_view(),
         name='sound-detail'),

    path('sounds/exhibition/comment/create/',
         views.SoundscapeExhibitionCommentCreateView.as_view(),
         name='sound-comment-create'),

    path('sounds/exhibition/comment/create/success/',
         views.SoundscapeExhibitionCommentCreateSuccessTemplateView.as_view(),
         name='sound-comment-create-success'),

    path('sounds/create/',
         views.SoundCreateView.as_view(),
         name='sound-create'),

    path('sounds/create/success/',
         views.SoundCreateSuccessTemplateView.as_view(),
         name='sound-create-success'),
]

django/researchdata/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.core.mail import send_mail
from django.urls import reverse_lazy
from datetime import timedelta, datetime


class SoundUploadCode(models.Model):
    """
    A unique, random 6 digit code that is given to a single user to upload a sound
    Only users with a code can upload sounds
    """

    code = models.CharField(max_length=255, unique=True)
    assigned_to = models.CharField(max_length=255, blank=True, null=True, help_text="Input identifying information about which user this code has been assigned to (e.g. name, email)")
    admin_notes = models.TextField(blank=True, null=True)

    @property
    def sounds_count(self):
        return self.sounds.count()

    def __str__(self):
        return f'#{self.id} - {self.code}'


class Sound(models.Model):
    """
    A Sound that a member of public shares with the project
    """

    sound_upload_code = models.ForeignKey(SoundUploadCode, related_name='sounds', on_delete=models.PROTECT, blank=True, null=True)
    sound = models.FileField(
        upload_to='researchdata/sounds/',
        help_text="Please upload your sound recording here<br>Будь ласка завантажте Ваш звукозапис сюди",
        verbose_name='Sound / Звук'
    )

    location = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="Please provide some brief information about where you made the recording - e.g. a suburb in Kyiv, etc.<br>Надайте коротку інформацію про те, де ви зробили запис, напр. передмістя в м. Києві тощо",
        verbose_name='location / Локація'
    )

    location_soundscape_exhibition = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Location shown publicly in the soundscape exhibition'
    )
    location_soundscape_exhibition_ukrainian = models.CharField(
        max_length=255, blank=True, null=True,
        verbose_name='Location shown publicly in the soundscape exhibition (Ukrainian translation)'
    )

    photo = models.ImageField(
        upload_to='researchdata/photos/',
        blank=True,
        null=True,
        help_text="Please upload a photo related to this sound, to be shown on the public soundscape exhibition"
    )

    recording_date = models.DateField(
        blank=True,
        null=True,
        verbose_name="date of recording / Дата запису",
        help_text="Please provide the date that the sound recording was produced<br>Будь ласка, вкажіть дату створення звукозапису."
    )
    recording_time = models.TimeField(
        blank=True,
        null=True,
        verbose_name="time of recording / Час запису",
        help_text="Please provide the time that the sound recording was produced (approximate hour, if exact time not known)<br>Будь ласка, вкажіть час, коли було створено звукозапис (приблизну годину доби, якщо точний час невідомий)"
    )

    description = models.TextField(
        blank=True,
        null=True,
        help_text="Please provide any important information about the recording - e.g. the main sounds that it captures, your feelings about the recording, etc.<br> Будь ласка, надайте будь-яку інформацію про запис – напр. основні звуки, які він вловлює, ваші почуття щодо запису тощо.",
        verbose_name='description / Опис'
    )
    description_ukrainian = models.TextField(blank=True, null=True, verbose_name='Description (Ukrainian translation)')

    interviewee_reflection = models.TextField(
        blank=True,
        null=True,
        help_text="Following an interview with author of this sound, include interesting reflections they've had about their submission"
    )
    interviewee_reflection_ukrainian = models.TextField(blank=True, null=True, verbose_name='Interviewee reflection (Ukrainian translation)')

    related_sounds = models.ManyToManyField("self", blank=True, through='SoundsRelationship')
    order_in_soundscape_exhibition = models.FloatField(
        default=0,
        help_text="Sounds will be shown in the public soundscape exhibition in order of this value from lowest to highest"
    )
    prompt_for_public_comments = models.TextField(blank=True, null=True, help_text="Provide a prompt (i.e. a question or statement) to encourage users to comment on this in the public website")
    prompt_for_public_comments_ukrainian = models.TextField(blank=True, null=True)
    admin_approved = models.BooleanField(default=False, help_text="Please tick this box if you're happy for this sound to be included in the public sound exhibition.")
    admin_notes = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def author(self):
        if self.sound_upload_code and self.sound_upload_code.assigned_to:
            return self.sound_upload_code.assigned_to

    @property
    def title_soundscape_exhibition(self):
        title = ''
        if self.location_soundscape_exhibition:
            title += self.location_soundscape_exhibition
        elif self.location:
            title += self.location
        if self.recording_date:
            title += f"<br>{self.recording_date.strftime('%d %B %Y')}"
        if self.recording_time:
            title += f"<br>{str(self.recording_time)[:5]}"
        return title if len(title) else str(self)

    @property
    def title_soundscape_exhibition_ukrainian(self):
        title = ''
        if self.location_soundscape_exhibition_ukrainian:
            title += self.location_soundscape_exhibition_ukrainian
        elif self.location:
            title += self.location
        if self.recording_date:
            title += f'<br>{self.recording_date}'
        if self.recording_time:
            title += f' {str(self.recording_time)[:5]}'
        return title if len(title) else str(self)

    @property
    def description_preview(self):
        if self.description:
            return f'{self.description[:100]}...' if len(self.description) > 100 else self.description

    @property
    def description_ukrainian_preview(self):
        if self.description_ukrainian:
            return f'{self.description_ukrainian[:100]}...' if len(self.description_ukrainian) > 100 else self.description_ukrainian

    @property
    def related_sounds_list(self):
        related_sounds = []
        for rs in SoundsRelationship.objects.filter(Q(sound_1=self) | Q(sound_2=self)):
            related_sound = rs.sound_1 if rs.sound_1 != self else rs.sound_2
            if related_sound.admin_approved:
                related_sounds.append({
                    'related_sound': related_sound,
                    'relationship_details': rs.relationship_details,
                    'relationship_details_ukrainian': rs.relationship_details_ukrainian
                })
        return related_sounds

    @property
    def comments_approved(self):
        return self.soundscape_exhibition_comment.filter(admin_approved=True).order_by('-created')

    def __str__(self):
        return f"Sound #{self.id}: created {str(self.created)[:16]}"

    def save(self, *args, **kwargs):
        # Prevent users from submitting duplicate sounds by
        # ignoring saves of matching records within the last 10 seconds
        ten_seconds_ago = datetime.now() - timedelta(seconds=10)
        if not Sound.objects.filter(
            sound_upload_code=self.sound_upload_code,
            location=self.location,
            description=self.description,
            created__gte=ten_seconds_ago
        ):
            super().save(*args, **kwargs)


class SoundsRelationship(models.Model):
    """
    A relationship between 2 Sound objects, including details about their relationship
    """

    sound_1 = models.ForeignKey(Sound, related_name='sound_relationship_1', on_delete=models.RESTRICT)
    sound_2 = models.ForeignKey(Sound, related_name='sound_relationship_2', on_delete=models.RESTRICT)
    relationship_details = models.TextField(blank=True, null=True)
    relationship_details_ukrainian = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Relationship between Sound #{self.sound_1.id} and Sound #{self.sound_2.id}"


class SoundscapeExhibitionComment(models.Model):
    """
    A comment made about a Sound in the soundscape exhibition
    """

    sound = models.ForeignKey(Sound, related_name='soundscape_exhibition_comment', on_delete=models.RESTRICT)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    admin_approved = models.BooleanField(default=False, help_text="Please tick this box if you're happy for this comment to be included on the public website.")

    def __str__(self):
        return f"A comment about Sound #{self.sound.id}"

    def save(self, *args, **kwargs):
        """
        When a new comment is created, email the research team
        """
        if self.created is None:
            link = ''.join([
                'https://rethinking-transitional-justice.bham.ac.uk',
                str(reverse_lazy('admin:researchdata_soundscapeexhibitioncomment_changelist'))
            ])
            try:
                send_mail(
                    'Rethinking Transitional Justice',
                    f'Someone has posted a new Soundscape Exhibition comment: {link}',
                    settings.DEFAULT_FROM_EMAIL,
                    settings.NOTIFICATION_EMAIL,
                    fail_silently=False
                )
            except Exception as e:
                print('Failed to send email:', e)
        super().save(*args, **kwargs)

django/researchdata/forms.py
from django import forms
from . import models
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.DateInput):
    input_type = 'time'


class SoundCreateForm(forms.ModelForm):
    """
    A form for users to submit a 'Sound' object
    """

    # Sound Upload Code (prevents unwanted people from uploading sound data)
    sound_upload_code = forms.CharField(
        label='Sound Upload Code / Код завантаження звукозапису',
        help_text="The 6 digit code provided to you by the research team that's required to upload sound data. Contact us for help if you're unsure.<br>6-значний код, наданий вам дослідницькою групою, необхідний для завантаження звукових даних. Зв’яжіться з нами стосовно питань, які у вас виникли"
    )

    # Google ReCaptcha
    captcha = ReCaptchaField(widget=ReCaptchaV3, label='')

    class Meta:
        model = models.Sound
        fields = (
            'sound_upload_code',
            'sound',
            'location',
            'recording_date',
            'recording_time',
            'description',
        )
        widgets = {
            'recording_date': DateInput(),
            'recording_time': TimeInput(),
        }

    def clean_sound_upload_code(self):
        """
        Ensure that the sound_upload_code matches an existing code.
        If not, show error.
        """
        cleaned_data = self.clean()
        sound_upload_code = cleaned_data.get('sound_upload_code')
        sound_upload_code_fk = models.SoundUploadCode.objects.filter(code=sound_upload_code).first()
        if sound_upload_code_fk is None:
            self.add_error(
                'sound_upload_code',
                "The sound upload code is not valid. Please contact us for help if needed / Код завантаження звуку недійсний. Будь ласка, зв'яжіться з нами, якщо Вам необхідна допомога"
            )
        return sound_upload_code_fk

django/researchdata/views.py
from django.views.generic import (ListView, DetailView, CreateView, TemplateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from . import forms, models


class SoundCreateView(CreateView):
    """
    Class-based view to show the 'share your sound' template
    """
    template_name = 'researchdata/sound-create.html'
    form_class = forms.SoundCreateForm
    success_url = reverse_lazy('researchdata:sound-create-success')


class SoundCreateSuccessTemplateView(TemplateView):
    """
    Class-based view to show the sound create success template
    """
    template_name = 'researchdata/sound-create-success.html'


class SoundWelcomeTemplateView(TemplateView):
    """
    Class-based view to show the sound welcome template
    """
    template_name = 'researchdata/sound-welcome.html'


class SoundListView(LoginRequiredMixin, ListView):
    """
    Class-based view to show the Sound list template
    """
    template_name = 'researchdata/sound-list.html'

    def get_queryset(self):
        queryset = models.Sound.objects.filter(admin_approved=True)
        # Search results
        search = self.request.GET.get('search', None)
        if search:
            queryset = queryset.filter(
                Q(sound__icontains=search) |
                Q(location__icontains=search) |
                Q(location_soundscape_exhibition__icontains=search) |
                Q(location_soundscape_exhibition_ukrainian__icontains=search) |
                Q(recording_date__icontains=search) |
                Q(recording_time__icontains=search) |
                Q(description__icontains=search) |
                Q(description_ukrainian__icontains=search) |
                Q(interviewee_reflection__icontains=search) |
                Q(interviewee_reflection_ukrainian__icontains=search) |
                Q(prompt_for_public_comments__icontains=search)
            )
        return queryset.order_by('order_in_soundscape_exhibition', '-id')


class SoundDetailView(LoginRequiredMixin, DetailView):
    """
    Class-based view to show the Sound detail template
    """
    template_name = 'researchdata/sound-detail.html'
    queryset = models.Sound.objects.filter(admin_approved=True)


class SoundscapeExhibitionCommentCreateView(LoginRequiredMixin, CreateView):
    """
    Class-based view to create a SoundscapeExhibitionComment
    """
    fields = ['sound', 'comment']
    model = models.SoundscapeExhibitionComment
    success_url = reverse_lazy('researchdata:sound-comment-create-success')


class SoundscapeExhibitionCommentCreateSuccessTemplateView(TemplateView):
    """
    Class-based view to show the SoundscapeExhibitionComment create success template
    """
    template_name = 'researchdata/sound-comment-create-success.html'

django/researchdata/templates/researchdata/language.html
<div id="lang">
    <span data-lang="eng">🇬🇧</span>
    <span data-lang="ukr">🇺🇦</span>
</div>

<script>
$(document).ready(function(){

    // User clicks language option
    $('span[data-lang]').on('click', function(){
        let lang = $(this).attr('data-lang');
        // Hide all languages
        $('.lang-eng, .lang-ukr').hide()
        // Show selected language
        $(`.lang-${lang}`).show();
        // Set lang as cookie
        document.cookie = `lang=${lang}; expires=Mon, 31 Dec 2070 23:59:59 GMT; path=/; Secure;`;
    });

    // Function to return the value of a cookie
    function getCookie(name){
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }

    // Set default language from cookie (if cookie not found, set as English)
    let defaultLang = getCookie('lang');
    if (typeof defaultLang === "undefined") defaultLang = 'eng';
    $(`span[data-lang="${defaultLang}"]`).trigger('click');

});
</script>

django/researchdata/templates/researchdata/sound-comment-create-success.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    {% include 'researchdata/language.html' %}

    <div class="container">
        <h2>
            <span class="lang-eng">Thanks!</span>
            <span class="lang-ukr">Дякуємо!</span>
        </h2>
        <p class="lang-eng">
            Your comment has been sent to us successfully. Once it's been reviewed and approved by the project team, it will appear on the public website.
        </p>
        <p class="lang-ukr">
            Ваш коментар успішно надіслано нам. Після того, як його перегляне та схвалить команда проекту, він з’явиться на загальнодоступному веб-сайті.
        </p>
        <a href="{% url 'researchdata:sound-list' %}" class="sound-primarylink">
            <span class="lang-eng">View Sounds</span>
            <span class="lang-ukr">Переглянути звукозаписи</span>
            <i class="fas fa-play"></i>
        </a>
    </div>

{% endblock %}

django/researchdata/templates/researchdata/sound-create-success.html
{% extends "base.html" %}
{% load static %}

{% block main %}

    <div class="container">
        <h2>Thanks! / Дякуємо!</h2>
        <p>
            Your sound recording has been sent to us successfully.
        </p>
        <p>
            Ваш звукозапис успішно надіслано нам.
        </p>
    </div>

{% endblock %}

django/researchdata/templates/researchdata/sound-create.html
{% extends "base.html" %}
{% load static %}

{% block main %}

    <div class="container">
        <h2>Upload New Sound / Завантаження звукозапису</h2>
        <form id="sound-create-form" enctype="multipart/form-data" name="form" method="POST" action="{% url 'researchdata:sound-create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-submit-notes">
                <p>
                    By submitting this form I understand that I am providing data for the Rethinking Transitional Justice research project, and that this data will be used for research purposes at the University of Birmingham.
                </p>
                <p>
                    Надсилаючи цю форму, я розумію, що надаю дані для дослідницького проекту «Переосмислення правосуддя перехідного періоду» та що ці дані будуть використані для дослідницьких цілей в Бірмінгемському університеті.
                </p>
            </div>
            <button id="sound-create-submit" type="submit">Upload / Завантажити</button>
        </form>
    </div>

{% endblock %}

django/researchdata/templates/researchdata/sound-detail.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    {% include 'researchdata/language.html' %}

    <div id="sound-detail" class="container">
        <!-- Back link -->
        <a href="{% url 'researchdata:sound-list' %}" class="sound-backlink">
            &lt;
            <span class="lang-eng">View all Sounds</span>
            <span class="lang-ukr">Переглянути звукозаписи</span>
        </a>
        <!-- Title -->
        <h2>
            <span class="lang-eng">{{ object.title_soundscape_exhibition | safe }}</span>
            <span class="lang-ukr">{{ object.title_soundscape_exhibition_ukrainian | safe }}</span>
        </h2>
        <!-- Audio -->
        <div id="sound-detail-audio">
            <h3>
                <span class="lang-eng">Listen to the sound</span>
                <span class="lang-ukr">Прослухати звукозапис</span>
            </h3>
            <audio controls>
                <source src="{{ object.sound.url }}">
            </audio>
        </div>
        <!-- Photo -->
        {% if object.photo %}
            <h3>
                <span class="lang-eng">Photograph to illustrate the sound</span>
                <span class="lang-ukr">Фотографія для ілюстрації звуку</span>
            </h3>
            <a href="{{ object.photo.url }}" id="sound-detail-photo-container" target="_blank">
                <img id="sound-detail-photo" src="{{ object.photo.url }}" alt="photograph of location of sound">
            </a>
        {% endif %}
        <!-- Description -->
        {% if object.description %}
            <div id="sound-detail-description">
                <h3>
                    <span class="lang-eng">Original description of this sound by the interviewee who recorded it</span>
                    <span class="lang-ukr">Оригінальний опис звукозапису від респондента, що його записав</span>
                </h3>
                <p class="lang-eng">{{ object.description | safe }}</p>
                <p class="lang-ukr">{{ object.description_ukrainian | safe }}</p>
            </div>
        {% endif %}
        <!-- Interview Reflection -->
        {% if object.interviewee_reflection %}
            <div id="sound-detail-reflection">
                <h3>
                    <span class="lang-eng">Interviewee's reflections/comments on the recording</span>
                    <span class="lang-ukr">Роздуми/коментарі респондента щодо звукозапису</span>
                </h3>
                <p class="lang-eng">{{ object.interviewee_reflection | safe }}</p>
                <p class="lang-ukr">{{ object.interviewee_reflection_ukrainian | safe }}</p>
            </div>
        {% endif %}
        <!-- Related Sounds -->
        {% if object.related_sounds_list %}
            <div id="sound-detail-relatedsounds">
                <h3>
                    <span class="lang-eng">Related sounds</span>
                    <span class="lang-ukr">Пов'язані звуки</span>
                </h3>
                {% for related_sound in object.related_sounds_list %}
                    <div class="sound-detail-relatedsounds-item">
                        <h4>
                            {{ related_sound.related_sound.title_soundscape_exhibition | safe }}
                        </h4>
                        <div>
                            <p class="lang-eng">{{ related_sound.relationship_details }}</p>
                            <p class="lang-ukr">{{ related_sound.relationship_details_ukrainian }}</p>
                        </div>
                        <a href="{% url 'researchdata:sound-detail' related_sound.related_sound.id %}" class="sound-primarylink">
                            <span class="lang-eng">View Sound</span>
                            <span class="lang-ukr">Переглянути звукозапис</span>
                            <i class="fas fa-play"></i>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <!-- Comments -->
        <div id="sound-detail-comments">
            <h3>
                <span class="lang-eng">Comments</span>
                <span class="lang-ukr">Коментарі</span>
            </h3>
            <div id="sound-detail-comments-prompt">
                {% if object.prompt_for_public_comments %}
                    <span class="lang-eng">{{ object.prompt_for_public_comments }}</span>
                    <span class="lang-ukr">{{ object.prompt_for_public_comments_ukrainian }}</span>
                {% else %}
                    <span class="lang-eng">Please share with us your thoughts about this recording (for example, how did you react to it and has it given you any new insights into the Russia-Ukraine war?)</span>
                    <span class="lang-ukr">Будь ласка, поділіться своїми думками з приводу даного звукозапису (наприклад, як ви відреагували на нього і чи він надав він Вам якесь нове уявлення про Російсько-Українську війну?)</span>
                {% endif %}
            </div>
            <div id="sound-detail-comments-new">
                <form action="{% url 'researchdata:sound-comment-create' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sound" value="{{ object.id }}">
                    <p>
                        <textarea id="id_comment" title="comment" name="comment"></textarea>
                    </p>
                    <div id="sound-detail-comments-new-disclaimer">
                        <div class="lang-eng">
                            By submitting this information, you're agreeing for your comment to be displayed publicly on this website.
                            <br>
                            All submissions are anonymous and will be approved before appearing on the website.
                        </div>
                        <div class="lang-ukr">
                            Надсилаючи дану інформацію, Bи погоджуєтеся на розміщення Вашого коментаря у загальному доступі на цьому веб-сайті.
                            <br>
                            Усі матеріали є анонімними та будуть попередньо затверджені перед опублікуванням на веб-сайті.
                        </div>
                    </div>
                    <button type="submit">
                        <span class="lang-eng">Send</span>
                        <span class="lang-ukr">Надіслати</span>
                        <i class="fas fa-paper-plane"></i>
                    </button>
                </form>
            </div>
            <div id="sound-detail-comments-existing">
                {% for comment in object.comments_approved %}
                    <div class="sound-detail-comments-existing-comment">
                        <div class="sound-detail-comments-existing-comment-created">
                            {{ comment.created }}
                        </div>
                        <div class="sound-detail-comments-existing-comment-text">
                            {{ comment.comment | linebreaks }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

django/researchdata/templates/researchdata/sound-list.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    {% include 'researchdata/language.html' %}

    <div id="sound-list" class="container">
        <!-- Back link -->
        <a href="{% url 'researchdata:sound-welcome' %}" class="sound-backlink">
            &lt;
            <span class="lang-eng">View Soundscape Introduction</span>
            <span class="lang-ukr">Перегляньте вступ до звукового пейзажу</span>
        </a>
        <!-- Title -->
        <h2>
            <span class="lang-eng">Soundscape Exhibition</span>
            <span class="lang-ukr">Виставка звукових ландшафтів</span>
        </h2>
        <!-- Search bar -->
        <form method="GET" id="sound-list-search">
            <div class="list-options-search">
                <label for="sound-list-search-input">
                    <span class="lang-eng">Search</span>
                    <span class="lang-ukr">Пошук</span>
                </label>
                <input type="text" name="search" title="search" id="sound-list-search-input"><!--
                --><button type="submit" value="Search" title="search button" id="sound-list-search-button">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>
        <!-- List items -->
        <div id="sound-list-items">
            {% for object in object_list %}
                <div class="sound-list-items-item">
                    {% if object.photo %}
                        <img class="sound-list-items-item-photo" src="{{ object.photo.url }}" alt="photograph of location of sound">
                    {% endif %}
                    <div class="sound-list-items-item-title">
                        <span class="lang-eng">{{ object.title_soundscape_exhibition | safe }}</span>
                        <span class="lang-ukr">{{ object.title_soundscape_exhibition_ukrainian | safe }}</span>
                    </div>
                    <div class="sound-list-items-item-details">
                        {% if object.description_preview %}
                            <span class="lang-eng">{{ object.description_preview }}</span>
                        {% endif %}
                        {% if object.description_ukrainian_preview %}
                            <span class="lang-ukr">{{ object.description_ukrainian_preview }}</span>
                        {% endif %}
                    </div>
                    <a href="{% url 'researchdata:sound-detail' object.id %}" class="sound-primarylink">
                        <span class="lang-eng">View Sound</span>
                        <span class="lang-ukr">Переглянути звукозапис</span>
                        <i class="fas fa-play"></i>
                    </a>
                </div>
            {% empty %}
                <div id="sound-list-items-empty">
                    No sounds found. Please adjust your search criteria or check back soon!
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        $(document).ready(function(){
            // Set input field values using data in the URL
            function setFieldValueFromUrl(formItemID, urlParameter, triggerChange=false){
                var value = new URL(window.location.href).searchParams.get(urlParameter);
                if (value) $('#' + formItemID).val(value);
            }
            setFieldValueFromUrl('sound-list-search-input', 'search');
        });
    </script>

{% endblock %}

django/researchdata/templates/researchdata/sound-welcome.html
{% extends "base.html" %}
{% load static %}

{% block body %}

    {% include 'researchdata/language.html' %}

    <div id="sound-welcome" class="container">
        <h2>
            <span class="lang-eng">Soundscape Exhibition</span>
            <span class="lang-ukr">Виставка звукових ландшафтів</span>
        </h2>

        <img class="sound-welcome-image" src="{% static 'images/photographs/7.jpg' %}" alt="'Victory of Life' by Eugenia Yablonovska-Grishchenko">
        <div class="photograph-credit">'Victory of Life' by Eugenia Yablonovska-Grishchenko</div>

        <div id="sound-welcome-content">
            <p class="lang-eng">
                Content coming soon...
            </p>
            <p class="lang-ukr">
                Content coming soon (Ukraine) ...
            </p>
        </div>

        <a href="{% url 'researchdata:sound-list' %}" class="sound-primarylink">
            <span class="lang-eng">View Sounds</span>
            <span class="lang-ukr">Переглянути звукозаписи</span>
            <i class="fas fa-play"></i>
        </a>
    </div>

{% endblock %}